import os
import unittest
from src.xiwen.utils.pinyin import get_pinyin, map_pinyin

PINYIN_PATH = os.path.join(
    os.getcwd(), "src", "resources", "assets", "hanzi_pinyin_characters.tsv.txt"
)

SIMP_HANZI_TO_PINYIN = {
    "爱": "ài",
    "八": "bā",
    "爸": "bà/ba",
    "吧": "ba/bā/pā",
    "白": "bái/bai/bó",
    "百": "bǎi/bó/mò",
    "班": "bān",
    "半": "bàn/pàn",
    "帮": "bāng",
    "包": "bāo/páo/fú",
    "杯": "bēi",
    "北": "běi/bèi",
    "备": "bèi",
    "本": "běn/bēn",
    "比": "bǐ/bì/pí/pǐ",
    "边": "biān/bian",
    "病": "bìng",
    "不": "bù/bu/fǒu/fōu/fū",
    "啊": "a/ā/è/á/ǎ/à",
    "安": "ān",
    "般": "bān/pán/bǎn/bō",
    "办": "bàn",
    "饱": "bǎo",
    "报": "bào/fù",
    "背": "bèi/bēi",
    "笔": "bǐ",
    "必": "bì",
    "变": "biàn",
    "便": "biàn/pián/biān",
    "遍": "biàn",
    "部": "bù/pǒu",
    "才": "cái/cai/zāi",
    "参": "cān/shēn/sān/cēn/càn/sǎn",
    "餐": "cān/sūn",
    "按": "àn",
    "把": "bǎ/bà/pá",
    "搬": "bān/sù",
    "保": "bǎo",
    "被": "bèi/bì/pī/pì",
    "币": "bì",
    "标": "biāo/biào",
    "播": "bō/bǒ",
    "补": "bǔ",
    "步": "bù",
    "材": "cái/cai",
    "彩": "cǎi/cai",
    "曾": "céng/zēng",
    "察": "chá/cuì",
    "阿": "ā/ē/ě/ǎ/à",
    "矮": "ǎi",
    "案": "àn",
    "暗": "àn",
    "巴": "ba/bā",
    "摆": "bǎi1",
    "败": "bài",
    "伴": "bàn/pàn3",
    "薄": "báo/bó/bù/bò7",
    "宝": "bǎo",
    "抱": "bào/pāo/pǒu",
    "贝": "bèi4",
    "倍": "bèi/péi4",
    "笨": "bèn",
    "毕": "bì8",
    "闭": "bì",
    "避": "bì",
    "编": "biān/biǎn/biàn",
    "辩": "biàn/pián/biǎn/bàn6",
    "冰": "bīng/níng",
    "碍": "ài/yí",
    "岸": "àn",
    "拔": "bá/ba/bō/bié/fá/bèi",
    "拜": "bài",
    "版": "bǎn",
    "扮": "ban/bàn/fěn/fēn/huǒ",
    "棒": "bàng",
    "悲": "bēi",
    "辈": "bèi",
    "鼻": "bí",
    "彼": "bǐ",
    "壁": "bì",
    "宾": "bīn",
    "饼": "bǐng/bing",
    "玻": "bō",
    "博": "bó",
    "猜": "cāi",
    "裁": "cái",
    "册": "cè",
    "叉": "chā/chá/chǎ/chà",
    "挨": "āi/ái",
    "傲": "ào/áo",
    "罢": "ba/bà/pí/pì/bǐ/bǎi",
    "榜": "bǎng/bēng/bàng/páng",
    "傍": "bàng/páng/bēng/péng",
    "胞": "bāo/páo/pào",
    "暴": "bào/pù/bó",
    "爆": "bào/bó",
    "奔": "bēn/bèn/fèn",
    "逼": "bī",
    "扁": "biǎn/piān/biān/pián",
    "拨": "bō/fá",
    "波": "bō/bēi/bì",
    "捕": "bǔ",
    "踩": "cǎi/kuí",
    "残": "cán",
    "惨": "cǎn",
    "仓": "cāng/chuàng",
    "藏": "cáng/zàng/zāng",
    "厕": "cè/cì/zè/si",
}

TRAD_HANZI_TO_PINYIN = {
    "愛": "ài",
    "八": "bā",
    "爸": "bà/ba",
    "吧": "ba/bā/pā",
    "白": "bái/bai/bó",
    "百": "bǎi/bó/mò",
    "班": "bān",
    "半": "bàn/pàn",
    "幫": "bāng",
    "包": "bāo/páo/fú",
    "杯": "bēi",
    "北": "běi/bèi",
    "備": "bèi",
    "本": "běn/bēn",
    "比": "bǐ/bì/pí/pǐ",
    "邊": "biān/bian",
    "別": "bié/biè",
    "彆": "biè",
    "病": "bìng",
    "不": "bù/bu/fǒu/fōu/fū",
    "啊": "a/ā/è/á/ǎ/à",
    "安": "ān",
    "般": "bān/pán/bǎn/bō",
    "板": "bǎn",
    "闆": "pǎn/bǎn",
    "辦": "bàn",
    "飽": "bǎo",
    "報": "bào/fù",
    "背": "bèi/bēi",
    "筆": "bǐ",
    "必": "bì",
    "變": "biàn",
    "便": "biàn/pián/biān",
    "遍": "biàn",
    "表": "biǎo",
    "錶": "biǎo",
    "部": "bù/pǒu",
    "才": "cái/cai/zāi",
    "參": "cān/shēn/sān/cēn/càn/sǎn",
    "餐": "cān/sūn",
    "按": "àn",
    "把": "bǎ/bà/pá",
    "搬": "bān/sù",
    "保": "bǎo",
    "被": "bèi/bì/pī/pì",
    "幣": "bì",
    "標": "biāo/biào",
    "並": "bìng/bàn/bàng",
    "併": "bìng",
    "播": "bō/bǒ",
    "補": "bǔ",
    "布": "bù",
    "佈": "bù",
    "步": "bù",
    "材": "cái/cai",
    "採": "cǎi",
    "采": "cǎi/cài",
    "彩": "cǎi/cai",
    "曾": "céng/zēng",
    "察": "chá/cuì",
    "阿": "ā/ē/ě/ǎ/à",
    "矮": "ǎi",
    "案": "àn",
    "暗": "àn",
    "巴": "ba/bā",
    "擺": "bǎi1",
    "敗": "bài",
    "伴": "bàn/pàn3",
    "薄": "báo/bó/bù/bò7",
    "寶": "bǎo",
    "抱": "bào/pāo/pǒu",
    "貝": "bèi4",
    "倍": "bèi/péi4",
    "笨": "bèn",
    "畢": "bì8",
    "閉": "bì",
    "避": "bì",
    "編": "biān/biǎn/biàn",
    "辯": "biàn/pián/biǎn/bàn6",
    "冰": "bīng/níng",
    "礙": "ài/yí",
    "岸": "àn",
    "拔": "bá/ba/bō/bié/fá/bèi",
    "拜": "bài",
    "版": "bǎn",
    "扮": "ban/bàn/fěn/fēn/huǒ",
    "棒": "bàng",
    "悲": "bēi",
    "輩": "bèi",
    "鼻": "bí",
    "彼": "bǐ",
    "壁": "bì",
    "賓": "bīn",
    "餅": "bǐng/bing",
    "玻": "bō",
    "博": "bó",
    "猜": "cāi",
    "裁": "cái",
    "冊": "cè",
    "叉": "chā/chá/chǎ/chà",
    "挨": "āi/ái",
    "傲": "ào/áo",
    "罷": "ba/bà/pí/pì/bǐ/bǎi",
    "榜": "bǎng/bēng/bàng/páng",
    "傍": "bàng/páng/bēng/péng",
    "胞": "bāo/páo/pào",
    "暴": "bào/pù/bó",
    "爆": "bào/bó",
    "奔": "bēn/bèn/fèn",
    "逼": "bī",
    "扁": "biǎn/piān/biān/pián",
    "撥": "bō/fá",
    "波": "bō/bēi/bì",
    "捕": "bǔ",
    "踩": "cǎi/kuí",
    "殘": "cán",
    "慘": "cǎn",
    "倉": "cāng/chuàng",
    "藏": "cáng/zàng/zāng",
    "廁": "cè/cì/zè/si",
}


class TestGetPinyin(unittest.TestCase):
    def test_get_pinyin(self):
        """Test pinyin emerges with expected values"""
        # Simplified
        hanzi, pinyin = get_pinyin(SIMP_HANZI_TO_PINYIN.keys(), SIMP_HANZI_TO_PINYIN)
        for i in range(len(pinyin)):
            self.assertEqual(pinyin[i], SIMP_HANZI_TO_PINYIN[hanzi[i]])
        # Traditional
        hanzi, pinyin = get_pinyin(TRAD_HANZI_TO_PINYIN.keys(), TRAD_HANZI_TO_PINYIN)
        for i in range(len(pinyin)):
            self.assertEqual(pinyin[i], TRAD_HANZI_TO_PINYIN[hanzi[i]])


class TestMapPinyin(unittest.TestCase):
    def test_map_pinyin(self):
        """Test hanzi pinyin map loads correctly"""
        hanzi_to_pinyin_dict = map_pinyin(PINYIN_PATH)
        self.assertEqual(len(hanzi_to_pinyin_dict), 41209)


if __name__ == "__main__":
    unittest.main()
